[[plugins]]
repo = "iamcco/markdown-preview.nvim"
on_ft = ["markdown", "pandoc.markdown", "rmd"]
build = ["sh", "-c", "cd app && npx --yes yarn install"]

[[plugins]]
repo = "kaarmu/typst.vim"
on_ft = "typst"
lua_after = '''
-- Wrapped TypstWatch Command with custom opener (because Rust's `open::with` not works properly now, on my MacOS at least)
vim.api.nvim_create_autocmd('FileType', {
	pattern = 'typst',
	callback = function()
		vim.fn.timer_start(100, function()
			vim.api.nvim_buf_create_user_command(0, 'TypstWatch', function(opts)
				-- Create temporary functions for silent execution
				local funcname = 'typst_cache_zcGJN0nypnqo'
				_G[funcname] = function()
					local root = vim.fs.dirname(vim.fs.find('.git', { path = vim.fn.expand '%', upward = true })[1])
					local args = root and { '--root', root, unpack(opts.fargs) } or opts.fargs
					vim.g.typst_cmd = vim.g.typst_cmd or 'typst'
					vim.fn['typst#watcher#TypstWatch'](unpack(args))
					_G[funcname] = nil
				end

				-- If the terminal-app is not WezTerm ↓
				if vim.fn.getenv 'WEZTERM_EXECUTABLE' == vim.NIL then
					vim.cmd('silent lua _G.' .. funcname .. '()')
					return
				end
				-- If the terminal-app is WezTerm ↓↓

				vim.g.typst_pdf_viewer = ':' -- Unix Dummy command
				vim.cmd('silent lua _G.' .. funcname .. '()')

				-- Setup the event watcher
				local handle = vim.uv.new_fs_event()
				if not handle then
					return
				end

				-- Stoppers of the event watcher
				local event_stopper = function()
					vim.uv.fs_event_stop(handle)
					handle:close()
				end
				local autocmd_ID, timeout_ID
				autocmd_ID = vim.api.nvim_create_autocmd('BufWipeout', {
					buffer = 0,
					callback = function()
						vim.fn.timer_stop(timeout_ID)
						event_stopper()
					end,
					once = true,
				})
				timeout_ID = vim.fn.timer_start(3000, function()
					vim.notify 'PDF not found in 3 seconds.'
					vim.api.nvim_del_autocmd(autocmd_ID)
					event_stopper()
				end)
				local function stop_all()
					vim.api.nvim_del_autocmd(autocmd_ID)
					vim.fn.timer_stop(timeout_ID)
					event_stopper()
				end

				local cwd = vim.fn.getcwd()
				vim.notify 'Searching the new PDF....'
				vim.uv.fs_event_start(handle, cwd, {
					recursive = true,
					pattern = '*.pdf',
				}, function(err, filename, events)
					if err then
						return
					end
					if events.change then
						vim.schedule(function()
							local prior_process_code = nil
							if vim.b.typst_pdf_pane then
								prior_process_code = vim.system { 'wezterm', 'cli', 'activate-pane', '--pane-id', vim.b
									.typst_pdf_pane }:wait().code
							end

							if prior_process_code ~= 0 then
								vim.system({ 'wezterm', 'cli', 'split-pane', '--right', '--', 'tdf', filename }, {
									cwd = cwd,
								}, function(out)
									if out.stdout then
										local num = tonumber(out.stdout)
										if not num then
											vim.notify('Error parsing pane-id: ' .. out.stdout)
											return
										end
										vim.b.typst_pdf_pane = num
									end
								end)
							end

							stop_all()
						end)
					end
				end)
			end, {
				nargs = '*',
				force = true,
			})
		end)
	end
})
'''

[[plugins]]
repo = "mattn/emmet-vim"
on_ft = ["html", "jsx", "tsx", "astro", "typescriptreact", "javascriptreact"]

[[plugins]]
repo = "ixru/nvim-markdown"
on_ft = "markdown"
lua_before = "vim.g.vim_markdown_no_default_key_mappings = 1"

[[plugins]]
repo = "DrKJeff16/wezterm-types"
start = true

[[plugins]]
repo = "folke/lazydev.nvim"
on_ft = "lua"
lua_after = '''
require 'lazydev'.setup {
	library = {
		{ path = '${3rd}/luv/library',                words = { 'vim%.uv' } },
		{ path = 'wezterm-types', mods = { 'wezterm' } },
	},
}
'''

[[plugins]]
repo = "saecki/crates.nvim@stable"
on_ft = "toml"
lua_after = "require 'crates'.setup()"

[[plugins]]
repo = "mrcjkb/rustaceanvim"
on_ft = "rust"

[[plugins]]
repo = "akinsho/flutter-tools.nvim"
on_ft = "dart"
lua_after = '''
require 'flutter-tools'.setup {
	flutter_lookup_cmd = 'mise where flutter',
	lsp = {
		color = {
			enabled = true,
			virtual_text = true
		}
	}
}
'''

[[plugins]]
repo = "MeanderingProgrammer/render-markdown.nvim"
on_ft = ["markdown", "mdx", "mstdn", "Avante"]
lua_after = '''
require 'render-markdown'.setup {
	heading = {
		width = 'block',
		left_pad = 0,
		right_pad = 4,
		icons = {},
	},
	render_modes = true,
	code = {
		width = 'block',
	},
	file_types = { 'markdown', 'mdx', 'mstdn', 'Avante' },
}
'''

[[plugins]]
repo = "JoosepAlviste/nvim-ts-context-commentstring"
on_event = "VeryLazy"
lua_after = '''
require 'ts_context_commentstring'.setup { enable_autocmd = false }
'''
