[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python", "node"]

[tools]
"gem:terminal-notifier" = "latest"
go = "1.25.5"
# "go:github.com/kahing/goofys" = "0.20.0"
node = "latest"
"npm:fish-lsp" = "latest"
"npm:takt" = "latest"
"npm:trash-cli" = "latest"
pnpm = "latest"
usage = "2"
